### ISSUE TITLE
keras fails on macOS

### ISSUE THREAD

**Issue by matthewberryman** [ajayhemanth/Machine-Learning-Workshop#7]
For one of our macOS users with R (sorry didn't check what version) installed via the standard R macOS installer, I saw a kernel crash on the `mnist <- dataset_mnist()` call due to a c++ ABI bug. I separately wrote out that object to an rds file and sent them that, and then had them run `mnist <- readRDS("~/Downloads/mnist.rds")` instead.

**Comment by matthewberryman** [comment]
Hi @ajayhemanth , you are correct, it's not just in downloading, but 
running the other test
```r
library('keras')
to_categorical(1:3)
```
resulted in the same error:
libc++abi: __cxa_guard_acquire detected recursive initialization
[1]    77982 abort      R

I tried updating Rcpp alone but that ended up still crashing (just with R terminated, rather than the libc++ ABI error). It seems there is some conflict between the keras python package and the keras R package that was installed on these machines. Since the keras R package has an `install_keras()` command that installs the version of the the keras python package that matches and works. It gives a warning about a higher h5py 

It seems to me that it is a slightly simpler method for installing the dependencies in a way (since it's one line of R code rather than two terminal commands for keras and tensorflow python) that ensures the correct python packages get installed. I will try this out on Linux, macOS and Windows machines for good measure and submit a PR later.

**Comment by ajayhemanth** [comment]
Sounds good Matthew... [This thread](https://github.com/rstudio/rstudio/issues/5406#issuecomment-531320320) also discusses about the same... Let me know how it goes... Thanks...
