### ISSUE TITLE
install two required packages

### ISSUE THREAD

**Issue by jeromecy** [ajayhemanth/Machine-Learning-Workshop#8]
Two packages that are required in the analysis are not installed.

install.packages(c("plotly","plot.matrix"))

**Comment by matthewberryman** [comment]
Yes I have added those plus the h2o one in https://github.com/CBADS-SPI/Machine-Leaning-Workshop/blob/R_packages/1.%20Setup.ipynb in https://github.com/ajayhemanth/Machine-Leaning-Workshop/pull/2 - awaiting this to be merged by repo owners

**Comment by ajayhemanth** [comment]
merged... thank you for flagging ...
